[linux]
alacritty = "~/.alacritty.yml"
conky = "~/.conky.conf"
conky_shortcuts = "~/.conky_shortcuts.conf"
dunst = "~/.config/dunst"
emacs = "~/.emacs"
i3 = "~/.config/i3"
nvim = "~/.config/nvim"
screenrc = "~/.screenrc"
starship = "~/.config/starship.toml"
termite = "~/.config/termite"
vifm = "~/.config/vifm"
zshrc = "~/.zshrc"
